### ISSUE TITLE
Project not on NPM

### ISSUE THREAD

**Issue by mvarendorff2** [LiamAttClarke/svg-plotter#14]
The README.md states:

> Install using npm:
> 
> `npm install svg-plotter`

Doing so creates the following error:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/svg-plotter - Not found
npm ERR! 404
npm ERR! 404  'svg-plotter@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
Equally, the package is not available on the NPM website either: https://www.npmjs.com/package/svg-plotter

Was this intentional? If so, I could provide a docs update to install the project from git instead if that's something you might be interested in!

**Comment by LiamAttClarke** [comment]
Hey @mvarendorff2, thanks for posting and apologies for the (very) late response.

It was my intention to publish but I never got around to it. I'll take some time now to do some maintenance and will publish shorty after

**Comment by LiamAttClarke** [comment]
Published: https://www.npmjs.com/package/svg-plotter

**Comment by LiamAttClarke** [comment]
Published: https://www.npmjs.com/package/svg-plotter

**Comment by mvarendorff2** [comment]
Awesome, thank you ❤️
